### ISSUE TITLE
Автоматизация тестов для Story 1

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/16VTb#6]
Автоматизировать [сценарии ](https://github.com/Students-of-the-city-of-Kostroma/16VTb/issues/2) для [Story 1](https://github.com/Students-of-the-city-of-Kostroma/16VTb/issues/1)

**Comment by serega111198** [comment]
Создана ветка "issue-6" для решения данной проблемы
