### ISSUE TITLE
Разработка сценариев для Story 7

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/16VTb#8]
[Story 7](https://github.com/Students-of-the-city-of-Kostroma/16VTb/issues/7)

**Comment by halfer44** [comment]
[Test.docx](https://github.com/Students-of-the-city-of-Kostroma/16VTb/files/2025221/Test.docx)

**Comment by halfer44** [comment]
[тест.xlsx](https://github.com/Students-of-the-city-of-Kostroma/16VTb/files/2029626/default.xlsx)
